### ISSUE TITLE
Bot nemá rád špenát

### ISSUE THREAD

**Issue by Khubajsn** [Inkluzitron/Inkluzitron#139]
```
$vote Co je vic normalni davat na pizzu
:leafy_green: Spenat
konec za 200 minut
```

```
Duhový pes 🌈 BOT
Na řádku 🥬  Spenat byla očekávána jedna z následujících možností:
• možnost hlasování (emote␣text odpovědi)
• absolutní konec hlasování (konec␣datum a čas)
• relativní konec hlasování (konec␣za␣čas)
```

Vypadá to, že [EmoteReader](https://github.com/Inkluzitron/Inkluzitron/blob/master/src/Inkluzitron/Modules/Vote/VoteDefinitionParser.cs#L50) nezvládá načíst špenát.

**Comment by Khubajsn** [comment]
Poznámky:
* Detekce emojis by šla předělat na magic oneliner regex: https://stackoverflow.com/a/48148218
* Taky by ty "možná-emojis" šly prostě nahodit jako reakce a v případě chyby (Discord HTTP error 400) prostě vypsat, že tohle se nepovedlo. Akorát by tím splynula error hláška "tahle reakce je z cizího serveru" a "tohle není reakce"

**Comment by janchaloupka** [comment]
Asi stačí vyřešit aktualizací knihovny [Unicode.net](https://github.com/neosmart/unicode.net/releases/tag/2.0)
