### ISSUE TITLE
Invite system

### ISSUE THREAD

**Issue by strudla** [Inkluzitron/Inkluzitron#19]
vytvorit invite prikaz `invite <user#id>/<int64 userid>` 
ktory by mohol byt obmedzeny pre uz verified ludi ci mensiu skupinu (mods/admins?) na zaklade roli/acl?

bot by nasledne
* poslal priamo one-use invite link pozvanemu do dms s kratkym expiry, alebo
* poslal kratky text v stylu "cauec, bol si pozvany na server xxx, ak sa chces pripojit, odpis `blabla` / daj emote na tuto spravu" a invite sa mu vygeneruje po tomto confirmu

(druha moznost predide tomu ze invite expiruje pokial ho dostane clovek co je afk)

bot by mohol drzat historiu stylom "kto pozval koho, aky invite id bol generovany, ci sa user pripojil alebo nie,..." (lebo audit logs su time limited, amoze byt benefical podobne info drzat dlhsie)

ad:
v pripade joinu cez invite prikaz je usere verified hned po pripojenu
v pripade joinu cez eg. znamy verejny no-expiry link (mimo invite) dostane pristup len do limitovaneho poctu roomiek)

**Comment by crackonosh** [comment]
Zaroven si myslim, ze by bylo dobre, aby se v ramci tohoto implementoval i nejaky ten verify system.
S tim ze nove prichozi by meli par textovych roomek, hlavne ty s pravidly a pak treba klasicky talkies.

Nekdo zminoval, ze by se "verifikovalo pomoci fotky", coz na jednu stranu je fajn, ale nemyslim si, ze bychom meli nutit nekoho se fotit proti jeho vuli. Tudiz by imo mohl byt omezeny pristup temto lidem napr. po dobu 1 tydne do nejakych vice "deep" roomek a ty se mi zpristupni az po tydnu, kdy se nejake "vedeni" shodne na tom, ze ho mezi sebou chceme (tohle si myslim, ze bude hl. vyuzitelne treba do budoucna, kdyz by sem mel prijit vylozene nekdo cizi).

**Comment by strudla** [comment]
^ sounds nice
mozno by som v tom pripade este rozlisil v history ludi co:
* boli invited
* boli verifikovany (kedy/kto/...)

**Comment by janch32** [comment]
No a co kdyby si "verifikací" musel projít každý bez ohledu na to, jak se sem dostal. 

S tím rozdílem, že ti co byli přímo pozvaní, tak by měli nějaký (asi teda hodně velký) "plusový body"?

Protože v plánu je že ten invite link může poslat každý uživatel, ne?

**Comment by theleteron** [comment]
Poslat link přímo pozvanému může být problém. Nejsem si jist že bot může poslat zprávu někomu s kým nesdílí server + možnost toho že daný člověk má zakázané DMs.

**Comment by crackonosh** [comment]
> Poslat link přímo pozvanému může být problém. Nejsem si jist že bot může poslat zprávu někomu s kým nesdílí server + možnost toho že daný člověk má zakázané DMs.

Tak by bot po napsani nejakeho commandu poslal link na invite na server pro 1 cloveka a ten link by poslal uzivateli do dm, ktery si ho vyzadal?
