### ISSUE TITLE
global tier list

### ISSUE THREAD

**Issue by strudla** [Inkluzitron/Inkluzitron#56]
namiesto sucasneho bdsm modulu ktory uklada len results z bdsmtest.org, moznost ukladat hodnoty aj z dalsich testov (#for-fellow-rice-enjoyers) - zaroven nepotreba spoliehat sa na rozne google docs/sheets/... ktore su (kinda) verejne dostupne

> [12:03] strudl: veci z #for-fellow-rice-enjoyers ?
> [12:07] Janch: Tu roomku vidím poprvé
> [12:11] strudl: ja cakal ze bude nejaky global tier list
> [12:11] strudl: a rozne weby a resulty z nich budu nejake sub commandy
> [12:13] Janch: Purity test by taky mohl být v botovi

**Comment by janch32** [comment]
Asi zavírám. Pro jednotlivý testy bude lepší udělat issues zvlášť. Asi nepůjde udělat ukládání výsledků obecně pro všechny druhy testů.

Pokud by s tím někdo nesouhlasil, nebudu naštavaný, když to znovu otevřete.
